export const STRUCTURE_IMPORT_ERROR_USERNAME_FORMAT: number = 1;
export const STRUCTURE_IMPORT_ERROR_PHONE_FORMAT: number = 2;
export const STRUCTURE_IMPORT_ERROR_EMAIL_FORMAT: number = 3;
export const STRUCTURE_IMPORT_ERROR_ALREADY_IN_COMPANY: number = 4; //用户已经注册公司了
export const STRUCTURE_IMPORT_ERROR_EMAIL_EXIST: number = 5;
export const STRUCTURE_IMPORT_ERROR_WORK_NAME_NULL: number = 6;
export const STRUCTURE_IMPORT_ERROR_PHONE_NULL: number = 7;
export const STRUCTURE_IMPORT_ERROR_EMAIL_NULL: number = 8;
